const products = [
  {
    title: "Magnetite",
    category: 8,
    price: 89.0,
    img: "./src/assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "./src/assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "./src/assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "./src/assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Pop Maluco",
    category: 1,
    price: 89.0,
    img: "./src/assets/img/3.jpg",
    band: "Maluco do Pop",
    year: 2029,
    id: 4,
  },
  {
    title: "As mais Brabas",
    category: 2,
    price: 76.0,
    img: "./src/assets/img/1.jpg",
    band: "Os Brabos",
    year: 1900,
    id: 5,
  },
  {
    title: "Sofrencia Total",
    category: 3,
    price: 60.0,
    img: "./src/assets/img/4.jpg",
    band: "Depressivos",
    year: 9026,
    id: 6,
  },
  {
    title: "Climas Carnavalescos",
    category: 4,
    price: 12.0,
    img: "./src/assets/img/3.jpg",
    band: "Sei La",
    year: 12,
    id: 7,
  },
  {
    title: "oãiaB",
    category: 5,
    price: 99.0,
    img: "./src/assets/img/1.jpg",
    band: "Baioneiros",
    year: 2097,
    id: 8,
  },
  {
    title: "Rap do NaRuTo",
    category: 6,
    price: 56.0,
    img: "./src/assets/img/3.jpg",
    band: "Player Tauz",
    year: 9999,
    id: 9,
  },
  {
    title: "Lo-fizinhos",
    category: 7,
    price: 65.0,
    img: "./src/assets/img/2.jpg",
    band: "A Menina Que Estuda",
    year: 2077,
    id: 10,
  },
  {
    title: "Relaxamento 200%",
    category: 9,
    price: 29.0,
    img: "./src/assets/img/4.jpg",
    band: "Marry",
    year: 4020,
    id: 12,
  },
  {
    title: "Leilão de Gado",
    category: 10,
    price: 81.0,
    img: "./src/assets/img/1.jpg",
    band: "Leiloeiros",
    year: 2000,
    id: 13,
  },
  {
    title: "Amem Irmão",
    category: 11,
    price: 96.0,
    img: "./src/assets/img/3.jpg",
    band: "Jesus",
    year: 1972,
    id: 14,
  },
  {
    title: "Pisadinha",
    category: 3,
    price: 69.0,
    img: "./src/assets/img/2.jpg",
    band: "Não Sei",
    year: 9009,
    id: 15,
  },
  {
    title: "Musicas Bailaveis",
    category: 4,
    price: 20.0,
    img: "./src/assets/img/2.jpg",
    band: "Carros Alegoricos",
    year: 1993,
    id: 16,
  },
  {
    title: "40 grau celcios",
    category: 5,
    price: 59.0,
    img: "./src/assets/img/3.jpg",
    band: "caixa d' água head",
    year: 7777,
    id: 17,
  },
  {
    title: "Rag Dragon Ball",
    category: 6,
    price: 98.0,
    img: "./src/assets/img/4.jpg",
    band: "7 Minutos",
    year: 2220,
    id: 18,
  },
  {
    title: "Outro Lo-fi",
    category: 7,
    price: 53.0,
    img: "./src/assets/img/1.jpg",
    band: "O gato dela",
    year: 7702,
    id: 19,
  },
  {
    title: "Musica Reggae:",
    category: 9,
    price: 52.0,
    img: "./src/assets/img/2.jpg",
    band: "0-0",
    year: 1993,
    id: 20,
  },
  {
    title: "Rei do Gado",
    category: 10,
    price: 48.0,
    img: "./src/assets/img/3.jpg",
    band: "Pra mim isso é country",
    year: 200,
    id: 21,
  },
  {
    title: "Amem Senhor",
    category: 11,
    price: 92.0,
    img: "./src/assets/img/1.jpg",
    band: "Deus",
    year: 0,
    id: 22,
  },
  
];

const categories = [
  "Todos",  0,
  "Pop",  1, 
  "MPB",  2,
  "Forró",  3,
  "Samba",  4,
  "Baião",  5,
  "Rap",  6,
  "Hip-Hop",  7,
  "Rock", 8,
  "Reggae", 9,
  "Country",  10,
  "Gospel", 11,
];
